sudo: required
services:
   - docker

before_install:
    - docker build -t laxman1983/Docker-react -f Dockerfile.dev .

script:
        - docker run laxman1983/Docker-react npm run test -- --coverage
